import os
from dotenv import load_dotenv

load_dotenv()

# Supabase
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
SUPABASE_JWT_SECRET = os.getenv("JWT_SECRET_KEY")
SUPABASE_ISSUER = "/auth/v1"
SUPABASE_AUDIENCE = os.getenv("SUPABASE_AUDIENCE", "authenticated")

# LLM
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
CHATBOT_LLM_MODEL = os.getenv("CHATBOT_LLM_MODEL", "llama-3.1-8b-instant")
GROK_API = os.getenv("GROK_API") or os.getenv("Grok_API")
GROK_API_BASE_URL = os.getenv("GROK_API_BASE_URL", "https://api.x.ai/v1")

# Fact Book
FACTBOOK_SYNC_TOKEN = os.getenv("FACTBOOK_SYNC_TOKEN")
FACTBOOK_DAWN_BASE_URL = os.getenv("FACTBOOK_DAWN_BASE_URL", "https://www.dawn.com")
FACTBOOK_GROK_MODEL = os.getenv("FACTBOOK_GROK_MODEL", "grok-4-1-fast-reasoning")
FACTBOOK_TOPIC_MODEL = os.getenv("FACTBOOK_TOPIC_MODEL", FACTBOOK_GROK_MODEL)
FACTBOOK_TIMEZONE = os.getenv("FACTBOOK_TIMEZONE", "Asia/Karachi")
FACTBOOK_MIN_DATE = os.getenv("FACTBOOK_MIN_DATE", "2026-01-01")
FACTBOOK_MAX_EDITORIALS_PER_DAY = int(os.getenv("FACTBOOK_MAX_EDITORIALS_PER_DAY", "40"))
FACTBOOK_MAX_CANDIDATE_LINKS = int(os.getenv("FACTBOOK_MAX_CANDIDATE_LINKS", "60"))
FACTBOOK_REQUEST_TIMEOUT_SECONDS = int(os.getenv("FACTBOOK_REQUEST_TIMEOUT_SECONDS", "30"))
FACTBOOK_AUTO_SYNC_TODAY_ON_EMPTY = os.getenv("FACTBOOK_AUTO_SYNC_TODAY_ON_EMPTY", "true").lower() == "true"
FACTBOOK_AUTO_SYNC_COOLDOWN_SECONDS = int(os.getenv("FACTBOOK_AUTO_SYNC_COOLDOWN_SECONDS", "900"))

# Current Affairs MCQ Sync
CURRENT_AFFAIRS_SYNC_TOKEN = os.getenv("CURRENT_AFFAIRS_SYNC_TOKEN")
CURRENT_AFFAIRS_GENRE_ID = os.getenv("CURRENT_AFFAIRS_GENRE_ID", "")
CURRENT_AFFAIRS_DAWN_LATEST_URL = os.getenv("CURRENT_AFFAIRS_DAWN_LATEST_URL", "https://www.dawn.com/latest-news")
CURRENT_AFFAIRS_DAWN_PAKISTAN_URL = os.getenv("CURRENT_AFFAIRS_DAWN_PAKISTAN_URL", "https://www.dawn.com/pakistan")
CURRENT_AFFAIRS_DAWN_WORLD_URL = os.getenv("CURRENT_AFFAIRS_DAWN_WORLD_URL", "https://www.dawn.com/world")
CURRENT_AFFAIRS_GROK_MODEL = os.getenv("CURRENT_AFFAIRS_GROK_MODEL", "grok-4-1-fast-reasoning")
CURRENT_AFFAIRS_REQUEST_TIMEOUT_SECONDS = int(os.getenv("CURRENT_AFFAIRS_REQUEST_TIMEOUT_SECONDS", "30"))
CURRENT_AFFAIRS_MAX_CANDIDATE_LINKS_PER_SECTION = int(os.getenv("CURRENT_AFFAIRS_MAX_CANDIDATE_LINKS_PER_SECTION", "80"))
CURRENT_AFFAIRS_MAX_SELECTED_HEADLINES = int(os.getenv("CURRENT_AFFAIRS_MAX_SELECTED_HEADLINES", "24"))
CURRENT_AFFAIRS_MIN_RELEVANCE_SCORE = int(os.getenv("CURRENT_AFFAIRS_MIN_RELEVANCE_SCORE", "2"))
CURRENT_AFFAIRS_MIN_LLM_SCORE = int(os.getenv("CURRENT_AFFAIRS_MIN_LLM_SCORE", "60"))
CURRENT_AFFAIRS_MCQS_PER_DAY = int(os.getenv("CURRENT_AFFAIRS_MCQS_PER_DAY", "20"))

# LangSmith
LANGSMITH_API_KEY = os.getenv("LANGSMITH_API_KEY")
LANGSMITH_PROJECT = os.getenv("LANGSMITH_PROJECT", "insightLLM")
LANGSMITH_TRACING = os.getenv("LANGSMITH_TRACING", "false").lower()

# OCR retry/concurrency settings
OCR_MAX_RETRIES = int(os.getenv("OCR_MAX_RETRIES", "3"))
OCR_RETRY_BASE_DELAY = float(os.getenv("OCR_RETRY_BASE_DELAY", "1.0"))
OCR_RETRY_MAX_DELAY = float(os.getenv("OCR_RETRY_MAX_DELAY", "60.0"))
OCR_RETRY_JITTER_RANGE = float(os.getenv("OCR_RETRY_JITTER_RANGE", "0.2"))
OCR_RATE_LIMIT_BASE_DELAY = float(os.getenv("OCR_RATE_LIMIT_BASE_DELAY", "5.0"))
OCR_RATE_LIMIT_MAX_DELAY = float(os.getenv("OCR_RATE_LIMIT_MAX_DELAY", "300.0"))
OCR_CONCURRENT_PAGES = int(os.getenv("OCR_CONCURRENT_PAGES", "1"))
OCR_BATCH_SIZE = int(os.getenv("OCR_BATCH_SIZE", "5"))
OCR_BATCH_FAILURE_THRESHOLD = float(os.getenv("OCR_BATCH_FAILURE_THRESHOLD", "0.5"))
OCR_ADAPTIVE_CONCURRENCY_ENABLED = os.getenv("OCR_ADAPTIVE_CONCURRENCY_ENABLED", "true")
OCR_ADAPTIVE_MIN_CONCURRENCY = int(os.getenv("OCR_ADAPTIVE_MIN_CONCURRENCY", "1"))
OCR_ADAPTIVE_MAX_CONCURRENCY = int(os.getenv("OCR_ADAPTIVE_MAX_CONCURRENCY", "4"))
OCR_ADAPTIVE_LATENCY_THRESHOLD_MS = float(os.getenv("OCR_ADAPTIVE_LATENCY_THRESHOLD_MS", "90000.0"))
OCR_ADAPTIVE_STABLE_BATCHES = int(os.getenv("OCR_ADAPTIVE_STABLE_BATCHES", "2"))
OCR_IMAGE_OPTIMIZATION_ENABLED = os.getenv("OCR_IMAGE_OPTIMIZATION_ENABLED", "true")
OCR_IMAGE_MAX_DIMENSION = int(os.getenv("OCR_IMAGE_MAX_DIMENSION", "2048"))
OCR_IMAGE_MIN_DIMENSION_FOR_OPTIMIZATION = int(os.getenv("OCR_IMAGE_MIN_DIMENSION_FOR_OPTIMIZATION", "1500"))
